### PR TITLE
libmeta dfgviewer

### PR DESCRIPTION
**Pull request by datazuul**
libmeta module for DFG-Viewer metadata: Links and Rights.

What about "sonatype-lift" bugs? Should I fix it? Are they gonna be fixed in all other libmeta-libs, too?

### CODE REVIEW

**Comment by rsteph-de** [comment]
Looks good for me so far.

It would be nice, if you check that the files comply with the MyCoRe Java Code Styles.
https://www.mycore.de/documentation/developer/codestyle/
Please provide an empty line at the bottom of each file.

Do you plan to provide the Builder implementations to be consistent with the other data model implementations?

Just tell me, when you are done, that I can take it from there (cleanup and implement the missing features, if necessary)

**Comment by datazuul** [comment]
* Yes, I will reformat code to apply MyCore-Styles.
* Yes, next steps will be to add builder and tests

**Comment by datazuul** [comment]
ok all vulnerabilities fixed

**Comment by rsteph-de** [comment]
Thank you for fixing the sonatype-liftbot issues. 
It was  integrated to learn and see how useful it's comments are for development.

Finally, 
would you please add the project / license header comment to the Java files and DFGViewer-XML schema.
copy from here: 
https://github.com/MyCoRe-Org/libmeta/blob/f3847d8531cef6b6e334d248c4f5127523f6641d/libmeta-mods/src/main/java/org/mycore/libmeta/mods/MODSXMLProcessor.java#L1

After that your PR is ready to be merged.

**Comment by datazuul** [comment]
ready to merge

**Review by rsteph-de — APPROVED** [review]
looks good for me, ready to merge

**Pull request merged**
